% Call this to include the Matpower library
function matpowerStartup(matpowerFolder)
addpath( ...
[matpowerFolder '\lib'], ...
[matpowerFolder '\lib\t'], ...
[matpowerFolder '\data'], ...
[matpowerFolder '\most\lib'], ...
[matpowerFolder '\most\lib\t'], ...
[matpowerFolder '\mp-opt-model\lib'], ...
[matpowerFolder '\mp-opt-model\lib\t'], ...
[matpowerFolder '\mips\lib'], ...
[matpowerFolder '\mips\lib\t'], ...
[matpowerFolder '\mptest\lib'], ...
[matpowerFolder '\mptest\lib\t'], ...
[matpowerFolder '\extras\maxloadlim'], ...
[matpowerFolder '\extras\maxloadlim\tests'], ...
[matpowerFolder '\extras\maxloadlim\examples'], ...
[matpowerFolder '\extras\misc'], ...
[matpowerFolder '\extras\reduction'], ...
[matpowerFolder '\extras\sdp_pf'], ...
[matpowerFolder '\extras\se'], ...
[matpowerFolder '\extras\smartmarket'], ...
[matpowerFolder '\extras\state_estimator'], ...
[matpowerFolder '\extras\syngrid\lib'], ...
[matpowerFolder '\extras\syngrid\lib\t'], ...
'-end' );

return